name: Fly Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno test -A --unstable
        env:
          INTEGRATION_TESTS: true
          POSTGRES_HOST: localhost 
          POSTGRES_PASSWORD: postgres
      - run: |
          cat << EOF > .prod.env
          ENV=prod
          HOSTNAME=https://poll.blue
          LOCALHOST=http://localhost:8000
          BSKY_USERNAME=poll.blue
          BSKY_PASSWORD=${{ secrets.BSKY_PASSWORD }}
          PG_USERNAME=postgres
          PG_PASSWORD=${{ secrets.PG_PASSWORD }}
          PG_HOST=poll-blue-db.internal
          PG_DATABASE=postgres
          EOF
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}